language: perl
perl:
  - "5.20"
#  - "5.18"
#  - "5.16"
#  - "5.14"
#  - "5.12"
#  - "5.10"

before_install: 
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential ncbi-blast+ hmmer emboss samtools zlib1g-dev libncurses5 libncurses5-dev libdb-dev git cpanminus
  - sudo cpanm Data::Stag DB_File

#install:
#  - cpanm --quiet --installdeps --notest --force .

script: ./build/ci/run_tests.sh

after_failure: cat /home/travis/.cpanm/build.log

branches:
  only:
    - master
