ltrharvest:
  - mintsd: 4
  - maxtsd: 6
  - minlenltr: 100
  - maxlenltr: 6000
  - mindistltr: 1500
  - maxdistltr: 25000
  - seedlength: 30
  - tsdradius: 60
  - xdrop: 5
  - swmat: 2 
  - swmis: -2
  - swins: -3
  - swdel: -3
  - overlaps: best
ltrdigest:
  - pptradius: 30
  - pptlen: 8 30
  - pptagpr: 0.25
  - uboxlen: 3 30
  - uboxutpr: 0.91
  - pbsradius: 30
  - pbslen: 11 30
  - pbsoffset: 0 5
  - pbstrnaoffset: 0 5
  - pbsmaxeditdist: 1
  - pdomevalue: 10E-6
  - pdomcutoff: NONE
  - maxgaplen: 50
